
name: appphp
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - appphpnet

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appphpnet

networks:
  appphpnet:
volumes:
  db_data:
